### ISSUE TITLE
The need for a go4

### ISSUE THREAD

**Issue by SchetininVitaliy** [evovch/ACCULINNA_go4_user_library#1]
Не смотря на присутствие необходимых хедеров go4 в go4pieces, при сборке все равно проверяется его наличие в системе.  Возможно ли полностью избавить библиотеку от прямой зависимости от go4? Или может быть сделать ее опциональной, включающейся по флагу cmake?

**Comment by evovch** [comment]
Done! See
commit 8fe042f79f07967175afc064aea5fdb2eb0491cc
