### ISSUE TITLE
code convention

### ISSUE THREAD

**Issue by SchetininVitaliy** [evovch/ACCULINNA_go4_user_library#13]
В связи с тем, что в ревью довольно много замечаний про стиль стоит сделать файлик с код конвенчион и соблюдать его ВСЕМ.

**Comment by evovch** [comment]
В принципе, мы же начали делать что-то такое вот тут:
http://er.jinr.ru/dev.html#code-convention-c
Не годится?
А вообще, обычно если ты что-то правишь в чужом коде, стилистику можно подглядеть в имеющемся коде вокруг. То есть, мне кажется, описывать где ставить пробел, запятую или скобку, не имеет смысла. Просто нужно подстраиваться. Не перелопачивать же теперь весь ER или AccDaq ради пробелов...

**Comment by SchetininVitaliy** [comment]
Ок

**Comment by evovch** [comment]
https://root.cern.ch/root/htmldoc/guides/users-guide/GettingStarted.html#conventions
