### ISSUE TITLE
getting DetEventStation by name in UserProcAdvMonitoring::BuildEvent

### ISSUE THREAD

**Issue by himyss** [evovch/ACCULINNA_go4_user_library#29]
I am working in my project fork
All following problems are related to the commit 2a11c39b7966f88cca3147381811596add927462 
"2D histo filling method constructed by NAMES"

I am trying to understand how should I fill such 2D histograms as beam profile at MWPC1, MWPC2 and target planes. 

I found that this condition is often satisfied, which means that sometimes there is no such station with the name "Beam_detector_MWPC1" https://github.com/himyss/ACCULINNA_go4_user_library/blob/2a11c39b7966f88cca3147381811596add927462/useranalysis/advmonitoring/UserProcAdvMonitoring.cxx#L286

I thought that we always create detectors,stations,TclonesArrays. So do i face such problem?

The only explanation I can find at the moment us that at the following line of UserProcRepacking task we are getting the NULL pointer:
https://github.com/himyss/ACCULINNA_go4_user_library/blob/2a11c39b7966f88cca3147381811596add927462/useranalysis/repacking/UserProcRepacking.cxx#L188

Also for me its not clear what is parameter "final" in this method:
TGo4EventElement *getEventElement(const char* name,Int_t final=0); 

I tried to process 1000 events from lmd file using run.sh. Only 124 of them did not satisfy both conditions:
	if(!stMWPC1) 
	if(!stMWPC2) 

Also I will be glad to here any your instruction about how should we deal with 2-D histograms.

**Comment by evovch** [comment]
First of all, the 'final' argument of the 'TGo4EventElement::getEventElement' method has a default value. So, a general advice would be the following: if you want to use a method and you don't know what the argument with a default value means, trust the developer and keep the value default, i.e. do not explicitly give the value at method call. So, all your calls to getEventElement() should have no second argument.

Also, I see lots of 'bad' code which should be cleaned up before even trying to be merged into 'master'.
Particularly, your numerous histograms in the 'ProcessMessage' method. They almost duplicate the functionality in the 'autohistos' part which is implemented over several files. We shall discuss everything later.

**Comment by himyss** [comment]
problem solved

**Comment by evovch** [comment]
Even if you realize that the problem was due to your misunderstanding, a short comment may help further contributors to avoid it.

**Comment by himyss** [comment]
The problem could be described this way:
I was trying to fill 2D histograms from MWPC1 and MWPC2 stations. But i did not check if the number of objects in TClonesArray of these stations is more than 0. There are few events when number of objects are 0. In such cases analysis stopped on this event.


	TClonesArray* v_MWPC1 = st_MWPC1->GetDetMessages();
	TClonesArray* v_MWPC2 = st_MWPC2->GetDetMessages();

	Int_t mx1 = v_MWPC1->GetEntriesFast();
	Int_t mx2 = v_MWPC2->GetEntriesFast();
	if(mx1<1 || mx2<1) { // THIS CHECK HAVE TO BE DONE
		return;
	}
	for(Int_t i = 0; i < mx1; i++){
		DetMessage *mes_MWPC1 = (DetMessage*)v_MWPC1->At(i);
		nx1.push_back(mes_MWPC1->GetStChannel());
	}
	for(Int_t i = 0; i < mx2; i++){
		DetMessage *mes_MWPC2 = (DetMessage*)v_MWPC2->At(i);
		nx2.push_back(mes_MWPC2->GetStChannel());
	}
