### ISSUE TITLE
Fix bug in UserParamBeamDetMonitoring.cxx

### ISSUE THREAD

**Issue by vratislav3** [evovch/ACCULINNA_go4_user_library#39]
Be so kind and replace line No.9 in UserParamBeamDetMonitoring.cxx from

fBeamDetName("Beam_detector_MWPC"),

to 

fBeamDetName("Beam_detector"),

.

**Comment by evovch** [comment]
commit 2eac88770087fa5ea6b35156fed58d1441289931
