### ISSUE TITLE
data interfaces

### ISSUE THREAD

**Issue by SchetininVitaliy** [evovch/ACCULINNA_go4_user_library#8]
Для работы не хватает интерфейсов к данным:

1) В DetEventStation к fDetMessages
2) В DetMessage стоит данные сделать закртыми и сделать к ним интерфейсы.

**Comment by evovch** [comment]
See
commit 6e2ab9cf47d5c849025968ef1805ec63dc0b27c8
Author: evovch <evovch@gmail.com>
Date:   Wed Aug 29 22:00:54 2018 +0300
